//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncControllerPrj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class infinite2025Entities1 : DbContext
    {
        public infinite2025Entities1()
            : base("name=infinite2025Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers1> Customers1 { get; set; }
        public virtual DbSet<Customersx> Customersxes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Department1> Departments1 { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employees2> Employees2 { get; set; }
        public virtual DbSet<Orders1> Orders1 { get; set; }
        public virtual DbSet<Orders3> Orders3 { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<tbldepartment> tbldepartments { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<storelog> storelogs { get; set; }
        public virtual DbSet<myview> myviews { get; set; }
        public virtual DbSet<ViewEmployeeDetails2> ViewEmployeeDetails2 { get; set; }
    
        [DbFunction("infinite2025Entities1", "getlastN_years")]
        public virtual IQueryable<getlastN_years_Result> getlastN_years(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getlastN_years_Result>("[infinite2025Entities1].[getlastN_years](@n)", nParameter);
        }
    
        public virtual int A1(Nullable<int> customerid, string customername)
        {
            var customeridParameter = customerid.HasValue ?
                new ObjectParameter("customerid", customerid) :
                new ObjectParameter("customerid", typeof(int));
    
            var customernameParameter = customername != null ?
                new ObjectParameter("customername", customername) :
                new ObjectParameter("customername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("A1", customeridParameter, customernameParameter);
        }
    
        public virtual int Addproc(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Addproc", aParameter, bParameter);
        }
    
        public virtual int Addproc1(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Addproc1", aParameter, bParameter);
        }
    
        public virtual int addproc2(Nullable<int> a, Nullable<int> b, ObjectParameter c, ObjectParameter d)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addproc2", aParameter, bParameter, c, d);
        }
    
        public virtual ObjectResult<alldetails_Result> alldetails(Nullable<int> start, Nullable<int> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<alldetails_Result>("alldetails", startParameter, endParameter);
        }
    
        public virtual int displaydata(string tbl)
        {
            var tblParameter = tbl != null ?
                new ObjectParameter("tbl", tbl) :
                new ObjectParameter("tbl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("displaydata", tblParameter);
        }
    
        public virtual int divide(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("divide", aParameter, bParameter);
        }
    
        public virtual int divided(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("divided", aParameter, bParameter);
        }
    
        public virtual ObjectResult<pro2_Result> pro2(Nullable<System.DateTime> startdate, Nullable<System.DateTime> enddate)
        {
            var startdateParameter = startdate.HasValue ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro2_Result>("pro2", startdateParameter, enddateParameter);
        }
    
        public virtual ObjectResult<pro3_Result> pro3(Nullable<int> custid, ObjectParameter orderid, ObjectParameter quantity)
        {
            var custidParameter = custid.HasValue ?
                new ObjectParameter("custid", custid) :
                new ObjectParameter("custid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro3_Result>("pro3", custidParameter, orderid, quantity);
        }
    
        public virtual ObjectResult<Nullable<int>> pro4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pro4");
        }
    
        public virtual int sp_getdata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getdata");
        }
    
        public virtual int sp_GetEmployeesByDOJ(Nullable<System.DateTime> d1, Nullable<System.DateTime> d2)
        {
            var d1Parameter = d1.HasValue ?
                new ObjectParameter("d1", d1) :
                new ObjectParameter("d1", typeof(System.DateTime));
    
            var d2Parameter = d2.HasValue ?
                new ObjectParameter("d2", d2) :
                new ObjectParameter("d2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetEmployeesByDOJ", d1Parameter, d2Parameter);
        }
    
        public virtual int spAddEmployee(string name, string department, Nullable<decimal> salary, ObjectParameter newEmployeeID)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddEmployee", nameParameter, departmentParameter, salaryParameter, newEmployeeID);
        }
    
        public virtual ObjectResult<spGetProductsByCategory_Result> spGetProductsByCategory(string product)
        {
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetProductsByCategory_Result>("spGetProductsByCategory", productParameter);
        }
    }
}
