//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncControllerPrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myview
    {
        public int Empid { get; set; }
        public string Empname { get; set; }
        public Nullable<int> Deptid { get; set; }
        public Nullable<System.DateTime> joinDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> AnnualSalary { get; set; }
    }
}
