//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncControllerPrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders3
    {
        public int OrderID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
