//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Database_First.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class infinite2025Entities : DbContext
    {
        public infinite2025Entities()
            : base("name=infinite2025Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers1> Customers1 { get; set; }
        public virtual DbSet<Customersx> Customersxes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Department1> Departments1 { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employees2> Employees2 { get; set; }
        public virtual DbSet<Orders1> Orders1 { get; set; }
        public virtual DbSet<Orders3> Orders3 { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<storelog> storelogs { get; set; }
    }
}
