//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Database_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class storelog
    {
        public int logid { get; set; }
        public string errormessage { get; set; }
        public Nullable<System.DateTime> errordate { get; set; }
    }
}
